[2024-10-17T04:09:56.642+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T04:09:56.730+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T04:09:56.772+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T04:09:56.775+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T04:09:56.838+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T04:09:56.876+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=506) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T04:09:56.888+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpmgwek6ge']
[2024-10-17T04:09:56.886+0000] {standard_task_runner.py:72} INFO - Started process 519 to run task
[2024-10-17T04:09:56.900+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask extract_task_api
[2024-10-17T04:09:57.594+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host 17ff951a544b
[2024-10-17T04:09:58.424+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T04:09:58.438+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T04:09:59.807+0000] {logging_mixin.py:190} INFO - Error getting price: 401, {"message":"No API key found in request"}
[2024-10-17T04:09:59.814+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 39, in append_to_data_price
    file_path = base_path / file
                ~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
[2024-10-17T04:09:59.875+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T040956, end_date=20241017T040959
[2024-10-17T04:09:59.902+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T04:09:59.903+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task extract_task_api (unsupported operand type(s) for /: 'PosixPath' and 'NoneType'; 519)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 39, in append_to_data_price
    file_path = base_path / file
                ~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
[2024-10-17T04:09:59.959+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T04:10:00.002+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T04:10:00.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-17T15:08:09.044+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T15:08:09.180+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T15:08:09.223+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T15:08:09.230+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T15:08:09.289+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T15:08:09.316+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T15:08:09.327+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2024-10-17T15:08:09.326+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmp5pegaokp']
[2024-10-17T15:08:09.342+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask extract_task_api
[2024-10-17T15:08:09.624+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host df4e8ab00e1c
[2024-10-17T15:08:10.046+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T15:08:10.057+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T15:08:10.115+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: append_to_data_price() missing 1 required positional argument: 'file'
[2024-10-17T15:08:10.161+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T150809, end_date=20241017T150810
[2024-10-17T15:08:10.290+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T15:08:10.294+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task extract_task_api (append_to_data_price() missing 1 required positional argument: 'file'; 196)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: append_to_data_price() missing 1 required positional argument: 'file'
[2024-10-17T15:08:10.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T15:08:10.440+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T15:08:10.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-17T16:07:17.170+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T16:07:17.265+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T16:07:17.319+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T16:07:17.321+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T16:07:17.389+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T16:07:17.446+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T16:07:17.451+0000] {standard_task_runner.py:72} INFO - Started process 122 to run task
[2024-10-17T16:07:17.461+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpafwiupgz']
[2024-10-17T16:07:17.509+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask extract_task_api
[2024-10-17T16:07:17.997+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host 29817b8f615d
[2024-10-17T16:07:18.645+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T16:07:18.674+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T16:07:20.435+0000] {logging_mixin.py:190} INFO - Error getting price: 401, {"message":"No API key found in request"}
[2024-10-17T16:07:20.440+0000] {logging_mixin.py:190} INFO - None
[2024-10-17T16:07:20.469+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 54, in append_to_data_price
    if record['date'] in data_prices['date'].values:
       ~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-17T16:07:20.514+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T160717, end_date=20241017T160720
[2024-10-17T16:07:20.557+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T16:07:20.559+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task extract_task_api ('NoneType' object is not subscriptable; 122)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 54, in append_to_data_price
    if record['date'] in data_prices['date'].values:
       ~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-17T16:07:20.614+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T16:07:20.671+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T16:07:20.675+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-17T16:14:28.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T16:14:28.759+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T16:14:28.794+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T16:14:28.798+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T16:14:28.852+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T16:14:28.889+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T16:14:28.897+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2024-10-17T16:14:28.899+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmptqtq92w2']
[2024-10-17T16:14:28.923+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask extract_task_api
[2024-10-17T16:14:29.206+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host 1ab1bf654054
[2024-10-17T16:14:29.685+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T16:14:29.695+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T16:14:30.511+0000] {logging_mixin.py:190} INFO - Error getting price: 401, {"message":"No API key found in request"}
[2024-10-17T16:14:30.516+0000] {logging_mixin.py:190} INFO - None
[2024-10-17T16:14:30.530+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 54, in append_to_data_price
    if record['date'] in data_prices['date'].values:
       ~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-17T16:14:30.579+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T161428, end_date=20241017T161430
[2024-10-17T16:14:30.606+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T16:14:30.608+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task extract_task_api ('NoneType' object is not subscriptable; 92)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/obtain_currency.py", line 54, in append_to_data_price
    if record['date'] in data_prices['date'].values:
       ~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-10-17T16:14:30.651+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-17T16:14:30.720+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T16:14:30.727+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-17T17:20:11.141+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T17:20:11.327+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T17:20:11.416+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T17:20:11.456+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T17:20:11.678+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T17:20:11.775+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T17:20:11.794+0000] {standard_task_runner.py:72} INFO - Started process 128 to run task
[2024-10-17T17:20:11.817+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmp5za7ubo8']
[2024-10-17T17:20:11.978+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask extract_task_api
[2024-10-17T17:20:12.926+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host 1652cc614667
[2024-10-17T17:20:14.825+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T17:20:14.840+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T17:20:22.976+0000] {logging_mixin.py:190} INFO - Current dolar rates: 980.250008 ARS
[2024-10-17T17:20:22.979+0000] {logging_mixin.py:190} INFO - {'date': '2024-10-17', 'price': 980.250008}
[2024-10-17T17:20:23.001+0000] {logging_mixin.py:190} INFO - Record of day 2024-10-17 just exist. Not add again.
[2024-10-17T17:20:23.001+0000] {python.py:240} INFO - Done. Returned value was:           date       price
0   2024-09-09  957.763020
1   2024-09-10  957.430504
2   2024-09-11  957.741278
3   2024-09-12  959.995667
4   2024-09-13  958.043112
5   2024-09-14  959.250402
6   2024-09-15  959.249945
7   2024-09-16  960.448297
8   2024-09-17  961.241401
9   2024-09-18  962.250058
10  2024-09-19  962.754297
11  2024-09-20  961.531104
12  2024-09-21  961.359012
13  2024-09-22  962.642198
14  2024-09-23  965.232700
15  2024-09-24  965.262902
16  2024-09-25  968.500099
17  2024-09-26  967.232698
18  2024-09-27  965.466231
19  2024-09-28  965.466231
20  2024-09-29  965.617504
21  2024-09-30  968.767443
22  2024-10-01  969.592296
23  2024-10-02  970.245698
24  2024-10-03  971.736897
25  2024-10-04  975.742773
26  2024-10-05  975.742773
27  2024-10-06  976.734404
28  2024-10-07  974.829898
29  2024-10-08  974.254402
30  2024-10-09  974.741097
31  2024-10-11  973.490388
32  2024-10-16  980.718400
33  2024-10-17  980.227502
[2024-10-17T17:20:23.122+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T17:20:23.124+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T172011, end_date=20241017T172023
[2024-10-17T17:20:23.163+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T17:20:23.189+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-17T17:20:23.193+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-17T22:09:00.940+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T22:09:00.995+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T22:09:01.021+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T22:09:01.023+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T22:09:01.072+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task_api> on 2024-10-16 00:00:00+00:00
[2024-10-17T22:09:01.089+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T22:09:01.094+0000] {standard_task_runner.py:72} INFO - Started process 161 to run task
[2024-10-17T22:09:01.100+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'extract_task_api', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmp5pu94p0b']
[2024-10-17T22:09:01.111+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask extract_task_api
[2024-10-17T22:09:01.358+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.extract_task_api scheduled__2024-10-16T00:00:00+00:00 [running]> on host d95e36bcd28a
[2024-10-17T22:09:02.034+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='extract_task_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T22:09:02.045+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T22:09:03.457+0000] {logging_mixin.py:190} INFO - Current dolar rates: 980.732026 ARS
[2024-10-17T22:09:03.466+0000] {logging_mixin.py:190} INFO - {'date': '2024-10-17', 'price': 980.732026}
[2024-10-17T22:09:03.498+0000] {logging_mixin.py:190} INFO - Record of day 2024-10-17 just exist. Not add again.
[2024-10-17T22:09:03.502+0000] {python.py:240} INFO - Done. Returned value was:           date       price
0   2024-09-09  957.763020
1   2024-09-10  957.430504
2   2024-09-11  957.741278
3   2024-09-12  959.995667
4   2024-09-13  958.043112
5   2024-09-14  959.250402
6   2024-09-15  959.249945
7   2024-09-16  960.448297
8   2024-09-17  961.241401
9   2024-09-18  962.250058
10  2024-09-19  962.754297
11  2024-09-20  961.531104
12  2024-09-21  961.359012
13  2024-09-22  962.642198
14  2024-09-23  965.232700
15  2024-09-24  965.262902
16  2024-09-25  968.500099
17  2024-09-26  967.232698
18  2024-09-27  965.466231
19  2024-09-28  965.466231
20  2024-09-29  965.617504
21  2024-09-30  968.767443
22  2024-10-01  969.592296
23  2024-10-02  970.245698
24  2024-10-03  971.736897
25  2024-10-04  975.742773
26  2024-10-05  975.742773
27  2024-10-06  976.734404
28  2024-10-07  974.829898
29  2024-10-08  974.254402
30  2024-10-09  974.741097
31  2024-10-11  973.490388
32  2024-10-16  980.718400
33  2024-10-17  980.227502
[2024-10-17T22:09:03.784+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T22:09:03.787+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=extract_task_api, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T220900, end_date=20241017T220903
[2024-10-17T22:09:03.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T22:09:04.055+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-17T22:09:04.060+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
